<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="footer-container">
    <div class="footer">
        <div class="block block-subscribe">
        <?php 

        echo $this->getLayout()
	          ->createBlock('Magento\Cms\Block\Block')
	          ->setBlockId('brandshop_footer')
	          ->toHtml(); 
     
	    ?>
        </div>
    </div>
</div>
