<div class="field tcagreecreateaccount required">
    <div class="control">
        <input type="checkbox" id="tcagreecreateaccount" name="tcagreecreateaccount" data-validate="{required:true}" class="input-checkbox checkbox required" value="1" checked required>
        <label for="tcagreecreateaccount" class="label">
            <?= __('I read and accept the privacy policy.') ?>
        </label>
    </div>
</div>