<?php
/*Home page image based advertisement*/
?>
<div class="component-wrap"> 
<section class="component C0059 flow-left">
    <div class="component-inner">
        <div class="square-partition tall"> 
            <div class="square main text-black">  
                    <div class="visual-area">
                        <img class="pc-lg lazyloaded" alt="" aria-hidden="true" src="<?= $block->getData('image_data1_img');?>"  > 
                    </div> 
                    <div class="bx_cnt_hm_adv75">
                        <div>
                        <?= $block->getData('image_data1_content');?>
                        </div>
                    <a class="act_btn bx_dt_btn75 " href="<?= $block->getData('image_data1_url');?>" target="_blank"  >
                <?= $block->getData('image_data1_url_text');?>
                </a>
                </div> 
            </div>
        </div>
         <div class="square-partition top"> 
            <div class="square sub length-md text-black">
                <div class="visual-area">
                    <img class="pc-lg lazyloaded" alt="" src="<?= $block->getData('image_data2_img');?>"  >
                    
                  </div>
                  <div class="bx_cnt_hm_adv75">
                        <div>
                        <?= $block->getData('image_data2_content');?>
                        </div>
                <a class="act_btn bx_dt_btn75 " href="<?= $block->getData('image_data2_url');?>" target="_blank"  >
                  <?= $block->getData('image_data2_url_text');?>
                </a> 
                </div>
            </div>

            <div class="square sub length-sm text-white">
                   <div class="visual-area">
                    <img class="pc-lg lazyloaded"  alt="" aria-hidden="true" src="<?= $block->getData('image_data3_img');?>" > 
                  </div> 
                  <div class="bx_cnt_hm_adv75">
                        <div>
                        <?= $block->getData('image_data3_content');?>
                        </div>
                  <a class="act_btn bx_dt_btn75 " href="<?= $block->getData('image_data3_url');?>" target="_blank"  >
                  <?= $block->getData('image_data3_url_text');?>
                </a> 
                </div>
            </div>
        </div>
        <div class="square-partition bottom"> 
            <div class="square sub length-md text-black">
                  <div class="visual-area">
                    <img class="pc-lg lazyloaded" alt=""  src="<?= $block->getData('image_data4_img');?>" > 
                  </div> 
                  <div class="bx_cnt_hm_adv75">
                        <div>
                        <?= $block->getData('image_data4_content');?>
                        </div>
                 <a class="act_btn bx_dt_btn75 " href="<?= $block->getData('image_data4_url');?>" target="_blank"  >
                  <?= $block->getData('image_data4_url_text');?>
                </a> 
                </div>
            </div>
			 <div class="square sub length-sm text-white">
                   <div class="visual-area">
                    <img class="pc-lg lazyloaded"  alt="" aria-hidden="true" src="<?= $block->getData('image_data5_img');?>" > 
                  </div> 
                  <div class="bx_cnt_hm_adv75">
                        <div>
                        <?= $block->getData('image_data5_content');?>
                        </div>
                  <a class="act_btn bx_dt_btn75 " href="<?= $block->getData('image_data5_url');?>" target="_blank"  >
                  <?= $block->getData('image_data5_url_text');?>
                </a>
                </div> 
            </div>
        </div>
    </div>
</section>

</div>