<?php
?>
<div class="carousel-box text-black slick-slide slick-current" >
<div>
<img src="<?= $block->getData("image_data_img");?>" alt="" class="web_img_84_lst"/>
<img src="<?= $block->getData("image_data_img_mobile");?>" alt="" class="mbl_im_img_84_lst"/>
<a class="categogbtn" href="<?= $block->getData("image_data_url");?>" target="_blank"><?= $block->getData("image_data_url_text");?></a>
</div>
</div>